sonar.projectKey=go-backend
sonar.projectName=Go Backend
sonar.projectVersion=1.0
sonar.language=go
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
sonar.sourceEncoding=UTF-8
